name: CI

on:
  push:
    branches: [ "*" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.1.0
      
    - name: list code
      run: ls
      
  Build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - uses: actions/checkout@v6.1.0
    
    - name: Build
      run: docker build . -t ahmedbahaamazen/weather-station:actions-${{ github.run_number }}
      
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v6.1.0
    
    - name: Build
      run: docker build . -t ahmedbahaamazen/weather-station:actions-${{ github.run_number }}

    - name: docker run
      run: docker run ahmedbahaamazen/weather-station:actions-${{ github.run_number }}
  Release:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - uses: actions/checkout@v6.1.0
    
    - name: Build
      run: docker build . -t ahmedbahaamazen/weather-station:actions-${{ github.run_number }}
      
    - name: push docker image
      run: |
        echo '${{ secrets.DOCKERPASSWORD }}' | docker login -u ${{ secrets.DOCKERUSERNAME }} --password-stdin
        docker push ahmedbahaamazen/weather-station:actions-${{ github.run_number }}
